# Generated by Django 2.2 on 2019-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of protocol')),
                ('number', models.IntegerField(max_length=50, verbose_name='protocol number')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='protocol description')),
            ],
        ),
    ]
