# Generated by Django 2.2 on 2019-07-07 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_auto_20190707_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='requested date'),
            preserve_default=False,
        ),
    ]
