# Generated by Django 2.2 on 2019-07-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_protocolrequest_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolresponse',
            name='pq',
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='pq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='protocol.ProtocolResponse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocolresponse',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=50, verbose_name='protocol status'),
        ),
    ]
