# Generated by Django 2.2 on 2019-07-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0005_auto_20190707_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolrequest',
            name='response',
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='respones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='protocol.ProtocolResponse'),
            preserve_default=False,
        ),
    ]
