# Generated by Django 2.2 on 2019-07-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_auto_20190707_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolrequest',
            old_name='respones',
            new_name='pq',
        ),
    ]
