# Generated by Django 2.2 on 2019-07-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0007_auto_20190707_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolrequest',
            old_name='pq',
            new_name='response',
        ),
    ]
