# Generated by Django 2.2 on 2019-07-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0009_auto_20190707_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolrequest',
            name='response',
        ),
        migrations.AddField(
            model_name='protocolresponse',
            name='response',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='protocol.ProtocolRequest'),
            preserve_default=False,
        ),
    ]
