# Generated by Django 2.2 on 2019-07-08 09:39

from django.db import migrations, models
import protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0010_auto_20190708_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolrequest',
            name='pi_email',
            field=models.EmailField(max_length=200, validators=[protocol.validators.validate_pi_email], verbose_name='PI email'),
        ),
    ]
