# Generated by Django 2.2 on 2019-07-08 13:52

from django.db import migrations, models
import protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0011_auto_20190708_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='protocol name')),
                ('number', models.IntegerField(blank=True, verbose_name='assigned protocol number')),
                ('approval_date', models.DateField(verbose_name='date of approval')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocolresponse',
            name='number',
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='email',
            field=models.EmailField(default=1, max_length=200, validators=[protocol.validators.validate_pi_email], verbose_name='email'),
            preserve_default=False,
        ),
    ]
