# Generated by Django 2.2 on 2019-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0015_auto_20190710_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
