# Generated by Django 2.2 on 2019-07-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0018_auto_20190710_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='protocol.ProtocolResponse'),
        ),
    ]
