# Generated by Django 2.2 on 2019-07-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0020_auto_20190710_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='approval_date',
            field=models.DateTimeField(verbose_name='date of approval'),
        ),
    ]
