# Generated by Django 2.2 on 2019-07-12 09:23

from django.db import migrations, models
import protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0021_auto_20190711_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolrequest',
            name='duration',
            field=models.DurationField(blank=True, help_text='length of the test', null=True, verbose_name='test duration'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='number',
            field=models.IntegerField(blank=True, validators=[protocol.validators.validate_protocol_number], verbose_name='assigned protocol number'),
        ),
    ]
