# Generated by Django 2.2 on 2019-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0022_auto_20190712_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolrequest',
            name='durationFrom',
            field=models.DateField(blank=True, null=True, verbose_name='start of study'),
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='durationUpto',
            field=models.DateField(blank=True, null=True, verbose_name='end of study'),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='duration',
            field=models.DurationField(blank=True, help_text='study duration', null=True, verbose_name='duration of study'),
        ),
    ]
