# Generated by Django 2.2 on 2019-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0023_auto_20190712_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolrequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='request_date',
            field=models.DateTimeField(verbose_name='requested date'),
        ),
    ]
