# Generated by Django 2.2 on 2019-07-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0024_auto_20190717_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolrequest',
            name='durationFrom',
        ),
        migrations.RemoveField(
            model_name='protocolrequest',
            name='durationUpto',
        ),
    ]
